num_episodes: 500
epochs: 10
buffer_size: 1000
minimal_size: 300
batch_size: 256
actor_lr: 0.0001
critic_lr: 0.003
update_interval: 40
hidden_dim: 64
gamma: 0.95
tau: 0.005  # 软更新参数

# PPO 参数
lmbda: 0.95
eps: 200
target_update: 10